timeout: 1200s
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/${PROJECT_ID}/eventssample/eventssample:c-$SHORT_SHA'
  - '--build-arg'
  - 'COMMIT_SHA=$SHORT_SHA'
  - '.'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/eventssample/eventssample:c-$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'beta'
  - 'run'
  - 'deploy'
  - 'eventssample'
  - '--image'
  - 'gcr.io/${PROJECT_ID}/eventssample/eventssample:c-$SHORT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-secrets=/app/keys/public/public-key.pem=JwtPublicKey:latest,/app/keys/private/private-key.pem=JwtPrivateKey:latest'
  - '--service-account=eventssample-sa@$PROJECT_ID.iam.gserviceaccount.com'
  - '--timeout=20m'
