steps:
# Deploy Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: "bash"
  args: 
    - '-c'
    - |
        gcloud beta run deploy \
        --region us-central1 \
        --platform managed \
        --allow-unauthenticated \
        --update-env-vars ProjectId=$PROJECT_ID \
        --update-secrets=ConnectionString=EventsConnectionString:2 \
        --source . \
        --vpc-connector=mongodb-vpc \
        eventssample